version: '3.8'

services:
  orders-app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ordersDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=tarik2000
    depends_on:
      - postgres-db
    networks:
      - app-network

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: ordersDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tarik2000
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
